# Generated by Django 3.1.4 on 2020-12-18 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('image_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/2020/12/18')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/2020/12/18')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/2020/12/18')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='images/2020/12/18')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='images/2020/12/18')),
            ],
        ),
    ]
