# Generated by Django 3.1.4 on 2020-12-31 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0002_auto_20201231_2350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='Images',
        ),
    ]
