# Generated by Django 3.1.4 on 2020-12-31 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0003_auto_20201231_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='allImages',
        ),
    ]
