# Generated by Django 3.1.4 on 2020-12-31 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0004_auto_20201231_2354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allImages',
            new_name='allImage',
        ),
    ]
